version: 2.1

jobs:
  test:
    docker:
      - image: node:14
    steps:
      - checkout
      - run:
          name: "Install node packages"
          command: "npm install"
      - run:
          name: "Run testing"
          command: "npm run test"

workflows:
  project-workflow:
    jobs:
      - test
      
# 1
